### ISSUE TITLE
Part of the ships placed off board!

### ISSUE THREAD

**Issue by ramosjos** [cs361fall2018/project-team32#3]
Part of the ships can be placed off of the the boards. This is not good as this decreases the size of the ship and decreases the possibility of getting bombed which is cheating. So we must add strict boundaries on the board.

**Comment by JordanNg** [comment]
I have created some code for placing ships off of the board in the board model under the placeShip function. I do not believe that it is being implemented properly and was wondering if someone could take a look at my code and see what I am doing wrong.

**Comment by JordanNg** [comment]
Got it.
