### ISSUE TITLE
Implement Captain's Quarters

### ISSUE THREAD

**Issue by JordanNg** [cs361fall2018/project-team32#33]
Hitting the captains quarters will automatically result in a sunk ship. Battleships and Destroyers captain's quarters are armored resulting in 2 hits on the captain's quarters for a sink.

**Comment by JordanNg** [comment]
Added unique Captain's Quarters to each ship. Armor needs to be implemented as well as displaying all hits on the ship.

**Comment by ramosjos** [comment]
Jordan finished this but had build issues so i copied the code and pushed it from my computer without the builderrors.
